[project]
dependencies = ["banana @ git+https://github.com/mtalarico/test-direct-dep"]
name = "carrot"
version = "0.1.0"
description = "c as in carrot"
readme = "README.md"
requires-python = ">=3.10"
